/*
 * This source file was generated by the Gradle 'init' task
 */
package calculator;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import calculator.parser.Parser;

class AppTest {

    @Test
    void 足し算() {
        var parser = new Parser();
        var node = parser.parse("3 + 5");
        assertEquals(8, node.get().intValue(), "足し算の結果が正しい");
    }

    @Test
    void 引き算() {
        var parser = new Parser();
        var node = parser.parse("12.3-7.8");
        assertEquals(4.5d, node.get().doubleValue(), 0.01, "引き算の結果が正しい");
    }

    @Test
    void 掛け算() {
        var parser = new Parser();
        var node = parser.parse(" 8 * 4 ");
        assertEquals(32, node.get().intValue(), "掛け算の結果が正しい");
    }

    @Test
    void 割り算() {
        var parser = new Parser();
        var node = parser.parse("8/4");
        assertEquals(2, node.get().intValue(), "掛け算の結果が正しい");
    }

    @Test
    void 足し算_3項目() {
        var parser = new Parser();
        var node = parser.parse("3 + 2 + 5");
        assertEquals(10, node.get().intValue(), "3つの足し算の結果が正しい");
    }

}
